#! /bin/sh

IMAGES_PATH="${1%/}"

if [ "${IMAGES_PATH}" = "" ]
then
	IMAGES_PATH="images"
fi

qemu-system-arm                                                    \
    -M vexpress-a9                                                 \
    -smp 2                                                         \
    -m 256                                                         \
    -kernel "${IMAGES_PATH}"/zImage                                \
    -dtb "${IMAGES_PATH}"/vexpress-v2p-ca9.dtb                     \
    -drive file="${IMAGES_PATH}"/rootfs.ext2,if=sd,format=raw      \
    -append "console=ttyAMA0,115200 rootwait root=/dev/mmcblk0"    \
    -serial stdio                                                  \
    -net nic,model=lan9118                                         \
    -net user                                                      \

